/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.introspect2.testproject;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan
public class Introspect2TestProject {
	public static void main(String args[]) {
		SpringApplication.run(Introspect2TestProject.class, args);
	}
}


